export const A = {
  page: {
    minHeight: '100vh', background: 'var(--bg)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    padding: '1.5rem',
  },
  card: {
    background: 'var(--bg2)',
    border: '1px solid var(--border)',
    borderRadius: '20px',
    padding: '2.25rem',
    width: '100%', maxWidth: '380px',
  },
  backBtn: {
    background: 'none', border: 'none',
    color: 'var(--text3)', fontSize: '12px',
    cursor: 'pointer', marginBottom: '1.75rem',
    display: 'flex', alignItems: 'center', gap: '4px',
    fontFamily: 'var(--font-display)',
    padding: 0,
  },
  logo: {
    fontSize: '22px', fontWeight: 800,
    color: 'var(--green)', marginBottom: '4px',
    letterSpacing: '-0.02em',
  },
  title: {
    fontSize: '18px', fontWeight: 700,
    color: 'var(--text)', marginBottom: '4px',
    letterSpacing: '-0.02em',
  },
  sub: {
    fontSize: '13px', color: 'var(--text2)',
    marginBottom: '1.75rem',
  },
  field: { marginBottom: '1rem' },
  label: {
    display: 'block', fontSize: '12px',
    color: 'var(--text2)', marginBottom: '6px',
    fontWeight: 500,
  },
  input: {
    width: '100%', padding: '10px 12px',
    background: 'var(--bg3)',
    border: '1px solid var(--border2)',
    borderRadius: '9px',
    color: 'var(--text)', fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.15s',
    fontFamily: 'var(--font-display)',
  },
  btnPrimary: {
    width: '100%', padding: '11px',
    background: 'var(--green)', color: 'var(--bg)',
    border: 'none', borderRadius: '9px',
    fontSize: '14px', fontWeight: 700,
    cursor: 'pointer', marginTop: '0.25rem',
    fontFamily: 'var(--font-display)',
    letterSpacing: '-0.01em',
    transition: 'background 0.15s',
  },
  divider: {
    display: 'flex', alignItems: 'center',
    gap: '10px', margin: '1.25rem 0',
  },
  dividerLine: { flex: 1, height: '1px', background: 'var(--border)' },
  dividerText: {
    fontSize: '11px', color: 'var(--text3)',
    fontFamily: 'var(--font-mono)', textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  googleBtn: {
    width: '100%', padding: '10px',
    background: 'var(--bg3)',
    border: '1px solid var(--border2)',
    borderRadius: '9px',
    color: 'var(--text)', fontSize: '13px',
    fontWeight: 500, cursor: 'pointer',
    display: 'flex', alignItems: 'center',
    justifyContent: 'center', gap: '8px',
    fontFamily: 'var(--font-display)',
    transition: 'border-color 0.15s',
  },
  error: {
    fontSize: '12px', color: 'var(--red)',
    background: 'rgba(255,69,96,0.08)',
    border: '1px solid rgba(255,69,96,0.2)',
    borderRadius: '8px', padding: '9px 12px',
    marginBottom: '1rem',
  },
  switchRow: {
    textAlign: 'center', marginTop: '1.25rem',
    fontSize: '13px', color: 'var(--text2)',
  },
  switchLink: {
    color: 'var(--green)', cursor: 'pointer',
    background: 'none', border: 'none',
    fontFamily: 'var(--font-display)',
    fontSize: '13px', fontWeight: 600,
    padding: 0,
  },
};
